name: Build theme & plugin ZIPs

on:
  workflow_dispatch: # اجرا فقط با دکمه "Run workflow"

jobs:
  build-zips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist folder
        run: mkdir -p dist

      - name: Zip theme
        run: |
          cd wp-content/themes
          zip -r ../../dist/emindy-theme.zip emindy

      - name: Zip plugin
        run: |
          cd wp-content/plugins
          zip -r ../../dist/emindy-core.zip emindy-core

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: emindy-zips
          path: dist/*.zip
